# Generated by Django 3.1.1 on 2021-02-07 02:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='latitude',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='answer',
            name='longitude',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateField(default=datetime.date(2021, 2, 6)),
        ),
    ]
