# Generated by Django 3.1.1 on 2021-02-07 04:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0002_auto_20210206_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answered_at',
            field=models.DateField(default=datetime.date(2021, 2, 7)),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateField(default=datetime.date(2021, 2, 7)),
        ),
    ]
